### ISSUE TITLE
As a user i have options of add, update and delete users and also forget password

### ISSUE THREAD

**Issue by anudeepmv** [anudeepmv/WEBSTER#16]

**Comment by lekhanaa17** [comment]
It would be better if you forget username option also as it happens sometimes. What exactly delete users means?

**Comment by vinaychakka** [comment]
It would be better if you add a recent activity option so that the users can know about the updates.

**Comment by anudeepmv** [comment]
As a user i have options of added, update and delete users and also forget password #16
